#!/bin/sh

if [ -n "$SUDO_USER" ]; then
	export USER=$SUDO_USER
fi

function clean_up {
	rm -rf /tmp/fuse-x-studio-mac.tgz
	rm -rf /tmp/install-fuse.sh
	rm -rf /tmp/get-version.js
	rm -rf /tmp/version-gte.js
}

function error {
	cat /tmp/install-fuse.log
	cat /tmp/install-fuse.err
	#clean_up
	exit 1
}

su "$USER" -c 'bash /tmp/install-fuse.sh || bash /tmp/install-fuse.sh || bash /tmp/install-fuse.sh' \
	2> /tmp/install-fuse.err > /tmp/install-fuse.log || error

echo Success
clean_up
