#!/bin/sh
PATH=/usr/local/bin:$PATH
NPM=npm

$NPM install -g /tmp/fuse-x-studio-mac.tgz || exit 1
ln -sf `$NPM prefix -g`/lib/node_modules/@fuse-x/studio-mac/bin/fuse\ X.app /Applications

# Reset permissions
chown -R root:wheel /Applications/fuse\ X.app
chmod +x /Applications/fuse\ X.app/Contents/SketchImporter/fondu
chmod -R a+rwx /Applications/fuse\ X.app/Contents/Modules

su "$USER" -c '/Applications/fuse\ X.app/Contents/MacOS/fuse\ X kill-all'
